FROM golang:alpine AS builder
WORKDIR /
ADD go.mod .
COPY . .
RUN go build -o migrate cmd/migrate/main.go

FROM alpine
WORKDIR /

ADD /configs /configs
ADD /migrations /migrations

RUN apk update
RUN apk add postgresql-client

COPY --from=builder /migrate /migrate
CMD ["./migrate"]