run:
	go run cmd/app/main.go

build:
	go build -o bin/app cmd/app/main.go

build-image:
	docker rmi go-service -f
	docker build -t go-service .

run-container:
	docker run -d -p 8080:8080 go-service

migrate-up:
	migrate -path ./migrations -database 'postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable' up

migrate-down:
	migrate -path ./migrations -database 'postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable' down